### ISSUE TITLE
"Unable to parse remote response: 401 Unauthorized" если хаб требует авторизации

### ISSUE THREAD

**Issue by Drenjy** [jdi-testing/jdi-light#1681]
В случае подключения с серверу [ggr](https://aerokube.com/ggr/latest/) с авторизацией пользователя выдаётся ошибка `java.lang.RuntimeException: 
Can't init 'page' 'usersPage' on 'SiteJdi'
Exception: 
Can't create field 'usersPage' instance of type 'class org.mytests.uiobjects.example.site.pages.UsersPage'. Try new class org.mytests.uiobjects.example.site.pages.UsersPage() to get more details
Exception: 

Can't init 'element' 'users' on 'UsersPage'
Exception: 
Setup rule 'Element' failed. Can't setup field 'users' on page 'UsersPage'
Exception: java.lang.RuntimeException: 
Setup element 'users' with Annotation 'Timeout' failed
Exception: java.lang.RuntimeException: java.lang.RuntimeException: 
Can't get driver; Thread: 1
Drivers: chrome:com.epam.jdi.light.driver.WebDriverFactory$$Lambda$127/1746076333@65c5c319; Run: Exception: java.lang.RuntimeException: 
Failed to setup remote chrome driver
Exception: Unable to parse remote response: 401 Unauthorized

Exception: java.lang.RuntimeException: 
Failed to setup remote chrome driver
Exception: Unable to parse remote response: 401 Unauthorized

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:25)
	at com.epam.jdi.light.elements.init.PageFactory.initialize(PageFactory.java:83)
	at com.epam.jdi.light.elements.init.PageFactory.initSite(PageFactory.java:74)
	at com.epam.jdi.light.elements.init.PageFactory.initSite(PageFactory.java:68)
	at org.mytests.tests.TestsInit.setUp(TestsInit.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:511)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:241)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:338)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
`
настройки файла tests.properties:
`driver=${driver}
#driver.version=2.23
timeout.wait.element=5
timeout.wait.page=25
domain=${domain}
#driver.getLatest=true
smart.locators=#%s
log.level=INFO
#search.element.strategy=strict | soft | visible, multiple | any, single
#assert.type=soft | strict

#page.load.strategy=normal
#browser.size=1800X1000
#drivers.folder=C:\\Selenium
#log.message.format=short | full
#cache=false | true
#demo.mode=false | true
#demo.delay=2
#remote.type=sauce | browserstack | selenium_localhost
driver.remote.url=http://test:test-password@domain:4444/wd/hub
#screenshot.strategy=on fail | on | off`
Проблема появилась пару недель назад, в прошлой версии (jdi-uitest-web:1.1.34) данной проблемы нет.

**Comment by Drenjy** [comment]
похоже что дефект в ggr https://github.com/aerokube/ggr/issues/301 https://github.com/aerokube/ggr/issues/297

Думаю можно откланить эту задачу.
