### ISSUE TITLE
(DEV branch) There are intermittent failures of features/Menu.feature tests.

### ISSUE THREAD

**Issue by 886-59-936** [jdi-testing/jdi-light#1692]
Each of features/Menu.feature tests passes when run separately.
But when tests are run simultaneously - only first one passes, next test fails with:

java.lang.NullPointerException
at com.epam.jdi.light.elements.init.entities.collection.EntitiesCollection.getUI(EntitiesCollection.java:82)
  at com.epam.jdi.bdd.stepdefs.MenuSteps.list(MenuSteps.java:20)
  at com.epam.jdi.bdd.stepdefs.MenuSteps.select(MenuSteps.java:25)
  at ✽.When I select "Contact form" in "Left Menu" menu(C:/Users/Evgeny_Filippov/Work/JDI/jdi-light/jdi-bdd-tests/src/test/resources/features/Menu.feature:11)

Menu element is not initialized after page reload.

**Comment by pnatashap** [comment]
Not actual
