### ISSUE TITLE
Create jdi-angular module

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1776]
Create jdi-angular module (in the same manner as it is done for Bootstrap)
Add jdi-html into dependency

**Comment by Sudalius** [comment]
Modules have been created and one test added with pages and classes like in Bootstrap branch.

But now we need to resolve an issue with test execution.

The issue is:

`java.lang.RuntimeException: java.lang.RuntimeException: 
Unknown SMART_SEARCH_NAME: 'kebab-case | camelCase | snake_case | PascalCase | UPPER_SNAKE_CASE'. Please correct value 'smart.locators.toName' in test.properties.Available names: [camelCase,snake_case,kebab-case,PascalCase,UPPER_SNAKE_CASE,First Upper Case,ALL UPPER CASE]

	at com.epam.jdi.tools.func.JAction1.execute(JAction1.java:16)
	at com.epam.jdi.tools.PropertyReader.fillAction(PropertyReader.java:75)
	at com.epam.jdi.light.settings.WebSettings.init(WebSettings.java:184)
	at com.epam.jdi.light.elements.init.PageFactory.initSite(PageFactory.java:45)
	at io.github.epam.TestsInit.setUp(TestsInit.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:345)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)`
