### ISSUE TITLE
Datatable: failed to execute dataRow()

### ISSUE THREAD

**Issue by Ammar-Barry** [jdi-testing/jdi-light#2204]
Исходный код:
![image](https://user-images.githubusercontent.com/57789178/88397927-4c480700-cdcd-11ea-8a2f-8c62f1e169a3.png)
![image](https://user-images.githubusercontent.com/57789178/88397939-50742480-cdcd-11ea-9c9f-9971a1cb1738.png)
Для этой таблицы -  companiesDataTable - работает  allData, dataRow(1). 
Ошибка searchRules  - на cell (1,1) или cell(COMPANY_NAME_HEADER, 1)
![image](https://user-images.githubusercontent.com/57789178/88395059-215bb400-cdc9-11ea-8eda-0e13bf230076.png)
Описание багов:
[DataTable bug description.txt](https://github.com/jdi-testing/jdi-light/files/4980602/DataTable.bug.description.txt)
[DataTable bug description. MyInit class.txt](https://github.com/jdi-testing/jdi-light/files/4980603/DataTable.bug.description.MyInit.class.txt)

**Comment by AlexeyGirin** [comment]
Скриншот не открывается

**Comment by alisevych** [comment]
The same error for allData() or cell(n, n) or cell(COLUMN_NAME, n)

**Comment by alisevych** [comment]
Обратите внимание на прикрепленные текстовые файлы. Там исходный код без лишних деталей - для ещё одного кейса.

**Comment by AlexeyGirin** [comment]
Customer reported the issue fixed.

**Comment by alisevych** [comment]
The bug reproduces on 1.2.21.

**Comment by alisevych** [comment]
list.start.index=1 (set in test.properties)

lettersDataTable.core().getText()
 - correct result
 
lettersDataTable.header()
 - correct result

lettersDataTable.count();
 - correct number
 
lettersDataTable.webRow (1);
 - correct result
 
lettersDataTable.row(1);
 - correct result
 
lettersDataTable.line(1);
 - correct result

lettersDataTable.dataRow(1);
 - ERROR
 "[39:00.363] Failed to execute 'DataTable.dataRow' for element 'Letters Data Table' during '20' seconds. Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)"

lettersDataTable.dataRow(2);
 - correct result

lettersDataTable.allData();
 - ERROR
 "[40:33.242] Failed to execute 'DataTable.allData' for element 'Letters Data Table' during '20' seconds. Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)"

**Comment by alisevych** [comment]
12:51:22.039 [main] STEP  JDI - Assert is 'Letters Data Table' not empty (LettersListPage.lettersDataTable (css='#letter-list-grid table'))
12:51:22.716 [main] STEP  JDI - Get row '1' for 'Letters Data Table' table (LettersListPage.lettersDataTable (css='#letter-list-grid table'))
12:51:45.081 [main] ERROR JDI - >>> LettersListPage.lettersDataTable (css='#letter-list-grid table')
12:51:45.492 [main] INFO  JDI - Screenshot: ***\target\.logs\screens\2020-10-07-12-51-45FailedDataRow.jpg
12:51:45.503 [main] ERROR JDI - Url: ***
12:51:45.503 [main] ERROR JDI - Failed actions chain: DataTable.dataRow(int:'1') > UIElement.getText() > UIElement.text(TextTypes:'SMART_TEXT') > UIElement.text(TextTypes:'TEXT')
12:51:45.512 [main] INFO  JDI - [AUT-INFO] Making screenshot 



java.lang.RuntimeException: [51:45.503] Failed to execute 'DataTable.dataRow' for element 'Letters Data Table' during '20' seconds. Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:28)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:366)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:14)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:44)
	at com.epam.jdi.light.elements.complex.table.DataTable.dataRow(DataTable.java:59)
	at com.***.site.tests.letters.CreateOldLetterTests.createLetterTest(CreateOldLetterTests.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.RuntimeException: Failed to execute 'DataTable.dataRow' for element 'Letters Data Table' during '20' seconds. Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:28)
	at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:643)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:39)
	... 26 more
Caused by: java.lang.RuntimeException: Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:28)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:366)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:14)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:44)
	at com.epam.jdi.light.elements.common.UIElement.getText(UIElement.java:185)
	at com.epam.jdi.light.elements.common.UIElement.getValue(UIElement.java:757)
	at com.epam.jdi.light.elements.complex.table.DataTable.lineToData(DataTable.java:426)
	at com.epam.jdi.light.elements.complex.table.DataTable.dataRow_aroundBody0(DataTable.java:64)
	at com.epam.jdi.light.elements.complex.table.DataTable$AjcClosure1.run(DataTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:51)
	at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:632)
	... 27 more
Caused by: java.lang.RuntimeException: Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:28)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:366)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:14)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:44)
	at com.epam.jdi.light.elements.common.UIElement.text(UIElement.java:688)
	at com.epam.jdi.light.elements.common.UIElement.getText_aroundBody14(UIElement.java:186)
	at com.epam.jdi.light.elements.common.UIElement$AjcClosure15.run(UIElement.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:51)
	at com.epam.jdi.light.actions.ActionHelper.defaultAction(ActionHelper.java:620)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:40)
	... 35 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Search rules failed for element. Please check base().searchRules() for element or in global settings(JDISettings.ELEMENT.searchRule)
	at com.epam.jdi.tools.Timer.throwException(Timer.java:114)
	at com.epam.jdi.tools.Timer.getResultByCondition(Timer.java:158)
	at com.epam.jdi.tools.Timer.getResult(Timer.java:144)
	at com.epam.jdi.light.elements.common.UIElement.text_aroundBody108(UIElement.java:689)
	at com.epam.jdi.light.elements.common.UIElement$AjcClosure109.run(UIElement.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:51)
	at com.epam.jdi.light.actions.ActionHelper.defaultAction(ActionHelper.java:620)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:40)
	... 42 more

**Comment by alisevych** [comment]
The table declaration and related classes:

    @UI("#letter-list-grid table")
    public static DataTable<LettersRow, LettersTableInfo> lettersDataTable;

import com.epam.jdi.light.elements.common.UIElement;
import com.epam.jdi.light.elements.composite.Section;
public class LettersRow extends Section {
    public UIElement icon;
    public UIElement date;
    public UIElement author;
    public UIElement patient;
    public UIElement toField;
    public UIElement letterStatus;
    public LettersTableBtnsItem actionBtns;
}

import com.epam.jdi.light.elements.composite.Section;
import com.epam.jdi.light.elements.pageobjects.annotations.locators.Css;
import com.epam.jdi.light.ui.html.elements.common.Button;
public class LettersTableBtnsItem extends Section {
    @Css(".js-client-grid-edit") public Button editBtn;
    @Css("a[title=View]") public Button viewBtn;
}

import com.epam.jdi.tools.DataClass;
public class LettersTableInfo extends DataClass<LettersTableInfo>{
    public String icon = "", date, author, patient, toField, letterStatus, actionBtns = "";
    public LettersTableInfo(){}
    public void setDate(String date) {
        this.date = date;
    }
    public String getDate() {
        return date;
    }
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getAuthor() {
        return author;
    }
    public void setPatient(String patient) {
        this.patient = patient;
    }
    public String getPatient() {
        return patient;
    }
    public void setToField(String toField) {
        this.toField = toField;
    }
    public String getToField() {
        return toField;
    }
    public void setLetterStatus(String letterStatus) {
        this.letterStatus = letterStatus;
    }
    public String getLetterStatus() {
        return letterStatus;
    }
    public String print() {
        return "Letter record{" +
                ...
                '}';
    }
}

**Comment by AlexeyGirin** [comment]
@RomanIovlev please have a look

**Comment by pnatashap** [comment]
проблема связана с чек-боксом в первой колонке, скорее всего исправлено
есть задача по добавлению такой таблицы на тестовый сайт и тестов на нее, чтобы не сломать
