### ISSUE TITLE
Switching the "jdi-light-html" dependency from version 1.2.15 to 1.2.16 causes an issue with the launch of the customer project

### ISSUE THREAD

**Issue by gbuh** [jdi-testing/jdi-light#2211]
**It is not reproduced on other projects at the moment. Only on an individual client environment with Windows10 OS. There is no issue with macOS.
After switching the project dependency "jdi-light-html" from version 1.2.15 to 1.2.16 maven connects selenium-java version 4.0.0-alpha-6 and the following error occurs during the execution of the somePage.open() method:**

50:36.483 [JDI:STEP]: Open 'Login Page'(url=http://example.com/login) (Login Page)
50:37.847 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
50:37.873 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Exporting webdriver.chrome.driver as C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\84.0.4147.30\chromedriver.exe
50:37.874 [JDI:INFO]: Download driver: 'CHROME X32' successfully
50:37.874 [JDI:INFO]: Use driver path: C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\84.0.4147.30\chromedriver.exe
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 2485
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
50:39.805 [JDI:ERROR]: >>> SomeSite.loginPage (url=http://example.com/login; title=Login)

java.lang.RuntimeException: java.lang.RuntimeException: 
Failed to do screenshot. No Drivers run

	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:16)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:35)
	at com.epam.jdi.light.elements.composite.WebPage.open(WebPage.java:163)
	at com.epam.jdi.light.elements.composite.WebPage.open(WebPage.java:171)
	at com.example.TestsInit.setUp(TestsInit.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.RuntimeException: 
Failed to do screenshot. No Drivers run
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:17)
	at com.epam.jdi.light.driver.ScreenshotMaker.takeScreenshot(ScreenshotMaker.java:51)
	at com.epam.jdi.light.driver.ScreenshotMaker.takeScreenshot(ScreenshotMaker.java:44)
	at com.epam.jdi.light.driver.ScreenshotMaker.takeScreen(ScreenshotMaker.java:32)
	at com.epam.jdi.light.actions.ActionHelper.logFailure(ActionHelper.java:293)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:274)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:14)
	... 22 more

Test ignored.

50:40.579 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
50:40.607 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Exporting webdriver.chrome.driver as C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\84.0.4147.30\chromedriver.exe
50:40.609 [JDI:INFO]: Download driver: 'CHROME X32' successfully
50:40.609 [JDI:INFO]: Use driver path: C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\84.0.4147.30\chromedriver.exe
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 26171
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

java.lang.RuntimeException: Can't get WebDriver

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:24)
	at com.epam.jdi.light.driver.WebDriverFactory.getDriver(WebDriverFactory.java:155)
	at com.example.TestsInit.closeCurrentBrowser(QvidentTestsInit.java:40)
	at com.example.TestsInit.closeBrowser(QvidentTestsInit.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:671)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:543)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Can't get driver; Thread: 1
Drivers: chrome:com.epam.jdi.light.driver.WebDriverFactory$$Lambda$162/1374596618@2d9b7ff9; Run: 
	at com.epam.jdi.tools.func.JFunc1.execute(JFunc1.java:15)
	at com.epam.jdi.light.driver.WebDriverFactory.getDriver(WebDriverFactory.java:163)
	at com.epam.jdi.light.driver.WebDriverFactory.getDriver(WebDriverFactory.java:151)
	... 34 more
Caused by: java.lang.RuntimeException: Can't get driver; Thread: 1
Drivers: chrome:com.epam.jdi.light.driver.WebDriverFactory$$Lambda$162/1374596618@2d9b7ff9; Run: 
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:24)
	at com.epam.jdi.light.driver.WebDriverFactory.getDriverByName(WebDriverFactory.java:102)
	at com.epam.jdi.tools.func.JFunc1.execute(JFunc1.java:13)
	... 36 more
Caused by: java.lang.RuntimeException: Failed to setup local driver
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:24)
	at com.epam.jdi.light.driver.get.DriverInfo.setupLocal(DriverInfo.java:107)
	at com.epam.jdi.light.driver.get.DriverInfo.getDriver(DriverInfo.java:52)
	at com.epam.jdi.light.driver.WebDriverFactory.initDriver(WebDriverFactory.java:126)
	at com.epam.jdi.light.driver.WebDriverFactory.lambda$0(WebDriverFactory.java:35)
	at com.epam.jdi.light.driver.WebDriverFactory.getDriverByName(WebDriverFactory.java:80)
	... 37 more
Caused by: java.lang.RuntimeException: 
com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:17)
	at com.epam.jdi.light.driver.get.DriverInfo.setupLocal(DriverInfo.java:105)
	... 41 more.

**After adding additional project dependency 'org.seleniumhq.selenium:selenium-java:3.141.59'
other error occurs (Allure issue) during the execution of the somePage.open() method.**

58:57.930 [JDI:STEP]: Open 'Login Page'(url=http://localhost:14102/redesign/dashboard) (Login Page)
58:59.05 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Using chromedriver 83.0.4103.39 (since Chrome 83 is installed in your machine)
58:59.25 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Exporting webdriver.chrome.driver as C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\83.0.4103.39\chromedriver.exe
58:59.26 [JDI:INFO]: Download driver: 'CHROME X32' successfully
58:59.27 [JDI:INFO]: Use driver path: C:\Users\user_name\.m2\repository\webdriver\chromedriver\win32\83.0.4103.39\chromedriver.exe
58:59.39 [JDI:INFO]: Failed to set Default Capabilities for Driver:
58:59.40 [JDI:INFO]: Errors: Chrome: '--disable-web-security', '--disable-extensions', 'test-type': org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chromium/ChromiumOptions;
Chrome: PageLoadStrategy:normal: org.openqa.selenium.chrome.ChromeOptions.setPageLoadStrategy(Lorg/openqa/selenium/PageLoadStrategy;)Lorg/openqa/selenium/remote/AbstractDriverOptions;
Chrome: setExperimentalOption: prefs: org.openqa.selenium.chrome.ChromeOptions.setExperimentalOption(Ljava/lang/String;Ljava/lang/Object;)Lorg/openqa/selenium/chromium/ChromiumOptions;
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 15040
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jul 20, 2020 1:59:02 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
59:05.784 [JDI:ERROR]: >>> QvidentSite.loginPage (url=http://localhost:14102/redesign/dashboard; title=Login)
59:06.495 [JDI:INFO]: Screenshot: C:\Users\Public\Projects\example\target\.logs\screens\screen2020-07-20-13-59-05.jpg

java.lang.NoSuchMethodError: io.qameta.allure.model.StepResult.setStatus(Lio/qameta/allure/model/Status;)V

	at com.epam.jdi.light.logger.AllureLogger.lambda$0(AllureLogger.java:43)
	at io.qameta.allure.AllureLifecycle.updateStep(AllureLifecycle.java:520)
	at com.epam.jdi.light.logger.AllureLogger.failStep(AllureLogger.java:43)
	at com.epam.jdi.light.actions.ActionHelper.logFailure(ActionHelper.java:305)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:274)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:14)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:35)
	at com.epam.jdi.light.elements.composite.WebPage.open(WebPage.java:163)
	at com.epam.jdi.light.elements.composite.WebPage.open(WebPage.java:171)
	at com.example.NavigationThroughSite.loginAsUser(NavigationThroughSite.java:22)
	at com.example.NavigationThroughSite.loginAsAdmin(NavigationThroughSite.java:33)
	at com.example.DataLoadActions.createUserWithRights(DataLoadActions.java:18)
	at com.example.tests.userProfile.EditUserProfileTests.createUserForTests(EditUserProfileTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

**Comment by gbuh** [comment]
Add the following dependency to the pom.xml file in the jdi-light module and rebuild the project.
<dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-model</artifactId>
            <version>RELEASE</version>
</dependency>
This fixed the problem for the customer.

**Comment by RomanIovlev** [comment]
fixed in 1.2.17

**Comment by gbuh** [comment]
Temporary approach to solving the issue until jdi-light v1.2.17 is released.
1. Download the next zip archive.
https://github.com/gbuh/jdi-temp/blob/master/jdi-light-1.2.16.zip
2. Extract 2 files jdi-light-1.2.16.jar and jdi-light-1.2.16.pom on the path to your local maven repository C:\Users\your_name\.m2\repository\com\epam\jdi\jdi-light\1.2.16. Replace existing files.
If you use gradle build tool the same extract and replace downloaded files for your local gradle repository C:\Users\your_name\.gradle\caches\modules-2\files-2.1\com\epam\jdi\jdi-light\1.2.16.
3. Update and resolve dependencies if needed.
4. Rebuild the project.
5. Run tests.
