### ISSUE TITLE
Executing setText(String value) (also sendKeys) method with input parameter value containing symbol ' or symbol $ gives Exception

### ISSUE THREAD

**Issue by callingelvis** [jdi-testing/jdi-light#231]
class: JDIBase (com.epam.jdi.light.elements.base.JDIBase.java)
method: setText(String value)

action: executing setText(String value) method with input parameter value containing symbol ' or symbol $ gives following exception:

>setText("I'm text")

```
java.lang.RuntimeException: 
[18:28.918] 
Failed to execute 'setText' for element 'Name' during '10' seconds. Exception: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected identifier
  (Session info: chrome=76.0.3809.100)
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'EPRUPETW0482', ip: '10.66.168.166', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.68 (420c9498db8ce..., userDataDir: C:\Users\EKATER~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:51184}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: b11d73d7ebbc27fc8f04f6b9353d500e

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:12)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:49)
	at com.epam.jdi.light.elements.base.JDIBase.setText(JDIBase.java:443)
	at com.epam.jdi.bdd.JDISteps.setText(JDISteps.java:97)
	at ✽.When Set text "I'm text" in "Name"(features/BaseUIElement.feature:98)
```

>setText("Five dollars = 5$")
```
java.lang.RuntimeException: 
[13:56.897] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Surround method issue: Can't get action name: Can't fill JDIAction template: Set '{0}' in '{name}'for method: setText

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:12)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:49)
	at com.epam.jdi.light.elements.base.JDIBase.setText(JDIBase.java:443)
	at com.epam.jdi.bdd.JDISteps.setText(JDISteps.java:97)
	at ✽.When Set text "Five dollars = 5$" in "Name"(features/BaseUIElement.feature:98)
```

**Comment by RomanIovlev** [comment]
Closed by https://github.com/jdi-testing/jdi-light/pull/260
