### ISSUE TITLE
StaleElementReferenceException при использовании JList

### ISSUE THREAD

**Issue by StrikS** [jdi-testing/jdi-light#2958]
Добрый день!
Задача проверить, что список результатов содержит нужную строку. Это таблица, но работаем со списками, так удобнее в данный момент.

Строка:
`resultList.assertThat().atLeast(1).elements(d -> d.getValue().contains(orgCaption));`
 
Падает с ошибкой: 
`Failed to execute 'Compare.elements' for element 'Result List' during '60' seconds. Can't do where:  org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document`
Ошибка плавающая, падает не каждый раз, но падает. Вероятно падает тогда, когда в процессе выполнения этой строки кода список результатов изменяется. Локатор корректен, список результатов в момент снятия скрина об ошибке не пуст.
<details>
  <summary>Более подробная информация об ошибке:</summary>

```
[55:09.369] Failed to execute 'Compare.elements' for element 'Result List' during '60' seconds. Can't do where:  org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document  (Session info: chrome=79.0.3945.79)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'azkasugf-asugfa1-job1-75', ip: '10.244.14.173', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.15.2.el7.x86_64', java.version: '1.8.0_282'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.79, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: /tmp/.com.google.Chrome.QFSmnJ}, goog:chromeOptions: {debuggerAddress: localhost:34200}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: 589ff229d7bb88b6ca49387aba469b7ab8f74e604b0bc5a0d06cbe5dab087c41. ]
 
java.lang.RuntimeException: [55:09.369] Failed to execute 'Compare.elements' for element 'Result List' during '60' seconds. Can't do where:  org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document  (Session info: chrome=79.0.3945.79)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'azkasugf-asugfa1-job1-75', ip: '10.244.14.173', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.15.2.el7.x86_64', java.version: '1.8.0_282'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.79, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: /tmp/.com.google.Chrome.QFSmnJ}, goog:chromeOptions: {debuggerAddress: localhost:34200}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: 589ff229d7bb88b6ca49387aba469b7ab8f74e604b0bc5a0d06cbe5dab087c41. ]
at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:19)
at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
at com.epam.jdi.light.asserts.generic.UISelectAssert$Compare.elements(UISelectAssert.java:184)
at com.bft.aisubp.pages.dictionaries.budgDictsPlan.budgDictsPlanExp.planFhd.fhdPlanStruct.sections.Results.select(Results.java:24)
at com.bft.aisubp.tests.dicts.FhdPlanStruct.FhdPlanStructTest.dTestFhdPlanStructChange(FhdPlanStructTest.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to execute 'Compare.elements' for element 'Result List' during '60' seconds. Can't do where: java.lang.RuntimeException: org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=79.0.3945.79)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'azkasugf-asugfa1-job1-75', ip: '10.244.14.173', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.15.2.el7.x86_64', java.version: '1.8.0_282'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.79, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: /tmp/.com.google.Chrome.QFSmnJ}, goog:chromeOptions: {debuggerAddress: localhost:34200}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: 589ff229d7bb88b6ca49387aba469b7ab8f74e604b0bc5a0d06cbe5dab087c41. ]
at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:636)
at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:48)
... 23 more
Caused by: java.lang.RuntimeException: Can't do where: java.lang.RuntimeException: org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=79.0.3945.79)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'azkasugf-asugfa1-job1-75', ip: '10.244.14.173', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.15.2.el7.x86_64', java.version: '1.8.0_282'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.79, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: /tmp/.com.google.Chrome.QFSmnJ}, goog:chromeOptions: {debuggerAddress: localhost:34200}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: 589ff229d7bb88b6ca49387aba469b7ab8f74e604b0bc5a0d06cbe5dab087c41. ]
at com.epam.jdi.tools.LinqUtils.exception(LinqUtils.java:708)
at com.epam.jdi.tools.LinqUtils.where(LinqUtils.java:176)
at com.epam.jdi.light.elements.complex.IList.where(IList.java:39)
at com.epam.jdi.light.elements.complex.IList.filter(IList.java:42)
at com.epam.jdi.light.asserts.generic.UISelectAssert$Compare.elements_aroundBody0(UISelectAssert.java:185)
at com.epam.jdi.light.asserts.generic.UISelectAssert$Compare$AjcClosure1.run(UISelectAssert.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:60)
at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:624)
... 24 more
```

</details>

Локатор:
```
@UI("//div[@id='center-container']//table[@role='grid'][@aria-labelledby='gbox_']//tr[@role='row']")
private JList<ResultRow> resultList;
```
 
Класс:
```
public class ResultRow extends UIElement {
    @UI("//td[@aria-describedby=\"_ORG_CAPTION\"]") public UIElement labelOrgCaption;
    @UI("//td[@aria-describedby=\"_TYPE_MODE\"]") public UIElement labelType;
    @UI("//td[@aria-describedby=\"_FTYPE\"]") public UIElement labelFType;
}
```

Мне казалось, что если список изменится, то выбросится ошибка StaleElementReferenceException, фреймворк перехватит её и продолжит попытки пока не истечёт таймаут. Просто при последующей попытке список обновится новыми значениями.
 
Есть идеи, что я делаю не так? Возможно упускаю что-то очевидное?

**Comment by AlexeyGirin** [comment]
![image](https://user-images.githubusercontent.com/26869421/153176938-efb642b0-15cb-44ed-848a-1839c1d556bd.png)
