### ISSUE TITLE
Проблемы с извлечением значений таблицы со страницы для DataTable

### ISSUE THREAD

**Issue by StrikS** [jdi-testing/jdi-light#2964]
### Исходные данные:
Есть таблица:
![изображение](https://user-images.githubusercontent.com/15943769/121325484-14857780-c92b-11eb-94a5-73521f0fca1e.png)

<details> 

<summary>Html код таблицы:</summary>

```<table cellspacing="0" cellpadding="0" border="0" role="grid" aria-multiselectable="true" aria-labelledby="gbox_" class="ui-jqgrid-btable" tabindex="-1" style="width: 910px;">
	<tbody>
		<tr id="1" role="row" class="ui-widget-content jqgrow ui-row-ltr">
			<td role="gridcell" aria-describedby="_cb" style="text-align:center;width: 25px;"><input role="checkbox" type="checkbox" id="jqg_1" class="cbox" name="jqg_1"></td>
			<td role="gridcell" style="text-align:left;display:none;width: 85px;" title="1001000000150" aria-describedby="_BUDGET_ID">1001000000150</td>
			<td role="gridcell" style="text-align: left; width: 455px;" title="Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов" aria-describedby="_BUDGET_CAPTION">Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов</td>
			<td role="gridcell" style="text-align: left; width: 159px;" title="ДОНМ" aria-describedby="_ORG_CAPTION">ДОНМ</td>
			<td role="gridcell" style="text-align: left; width: 103px;" title="Тип учреждения" aria-describedby="_TYPE_MODE">Тип учреждения</td>
			<td role="gridcell" style="text-align: left; width: 168px;" title="Для всех" aria-describedby="_FTYPE">Для всех</td>
			<td role="gridcell" style="text-align:left;display:none;width: 85px;" title="1001000005620" aria-describedby="_ID">1001000005620</td>
			<td role="gridcell" style="text-align:left;display:none;width: 70px;" title="1" aria-describedby="_VERSION">1</td>
		</tr>
		<tr id="2" role="row" class="ui-widget-content jqgrow ui-row-ltr">
			<td role="gridcell" aria-describedby="_cb" style="text-align:center;"><input role="checkbox" type="checkbox" id="jqg_2" class="cbox" name="jqg_2"></td>
			<td role="gridcell" style="text-align:left;display:none;" title="1001000000150" aria-describedby="_BUDGET_ID">1001000000150</td>
			<td role="gridcell" style="text-align:left;" title="Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов" aria-describedby="_BUDGET_CAPTION">Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов</td>
			<td role="gridcell" style="text-align:left;" title="Москомэкспертиза" aria-describedby="_ORG_CAPTION">Москомэкспертиза</td>
			<td role="gridcell" style="text-align:left;" title="Тип учреждения" aria-describedby="_TYPE_MODE">Тип учреждения</td>
			<td role="gridcell" style="text-align:left;" title="Для всех" aria-describedby="_FTYPE">Для всех</td>
			<td role="gridcell" style="text-align:left;display:none;" title="1001000005621" aria-describedby="_ID">1001000005621</td>
			<td role="gridcell" style="text-align:left;display:none;" title="1" aria-describedby="_VERSION">1</td>
		</tr>
		<tr id="3" role="row" class="ui-widget-content jqgrow ui-row-ltr">
			<td role="gridcell" aria-describedby="_cb" style="text-align:center;"><input role="checkbox" type="checkbox" id="jqg_3" class="cbox" name="jqg_3"></td>
			<td role="gridcell" style="text-align:left;display:none;" title="1001000000150" aria-describedby="_BUDGET_ID">1001000000150</td>
			<td role="gridcell" style="text-align:left;" title="Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов" aria-describedby="_BUDGET_CAPTION">Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов</td>
			<td role="gridcell" style="text-align:left;" title="Мосгоризбирком" aria-describedby="_ORG_CAPTION">Мосгоризбирком</td>
			<td role="gridcell" style="text-align:left;" title="Тип учреждения" aria-describedby="_TYPE_MODE">Тип учреждения</td>
			<td role="gridcell" style="text-align:left;" title="Бюджетное учреждение" aria-describedby="_FTYPE">Бюджетное учреждение</td>
			<td role="gridcell" style="text-align:left;display:none;" title="1001000005640" aria-describedby="_ID">1001000005640</td>
			<td role="gridcell" style="text-align:left;display:none;" title="1" aria-describedby="_VERSION">1</td>
		</tr>
	</tbody>
</table>
```

</details>

Переменная таблицы:
```
	@GetAny
	@UI("//table[@class='ui-jqgrid-btable']")
	public DataTable<ResultRow, ResultRowInfo> resultTable;
```
ResultRow:
```
	public class ResultRow extends Section {
	    @UI("//td[@aria-describedby='_cb']") public UIElement checkbox;
	    @GetAny @UI("//td[@aria-describedby='_BUDGET_ID']") public UIElement budgetId; // Невидимый столбец, т.к display:none
	    @UI("//td[@aria-describedby='_BUDGET_CAPTION']") public UIElement budgetCaption;
	    @UI("//td[@aria-describedby='_ORG_CAPTION']") public UIElement orgCaption;
	    @UI("//td[@aria-describedby='_TYPE_MODE']") public UIElement typeMode;
	    @UI("//td[@aria-describedby='_FTYPE']") public UIElement fType;
	}
```
	
ResultRowInfo:
```
	public class ResultRowInfo extends DataClass<ResultRowInfo> {
	    public String checkbox, budgetId, budgetCaption, orgCaption, typeMode, fType;
	}

```

----

### Результат:

<details> 
  <summary>При выполнении строк кода:</summary>

```
logger.info(results.resultTable.header().toString());
logger.info(results.resultTable.preview());
logger.info(results.resultTable.line(1).checkbox.getText());
logger.info(results.resultTable.line(1).budgetCaption.getText());
logger.info(results.resultTable.line(1).orgCaption.getText());
logger.info(results.resultTable.line(1).typeMode.getText());
logger.info(results.resultTable.line(1).fType.getText());
	
logger.info(results.resultTable.line(2).checkbox.getText());
logger.info(results.resultTable.line(2).budgetCaption.getText());
logger.info(results.resultTable.line(2).orgCaption.getText());
logger.info(results.resultTable.line(2).typeMode.getText());
logger.info(results.resultTable.line(2).fType.getText());
	
logger.info(results.resultTable.line(3).checkbox.getText());
logger.info(results.resultTable.line(3).budgetCaption.getText());
logger.info(results.resultTable.line(3).orgCaption.getText());
logger.info(results.resultTable.line(3).typeMode.getText());
logger.info(results.resultTable.line(3).fType.getText());
```

</details>

падает на строке `logger.info(results.resultTable.line(1).checkbox.getText());`
с ошибкой:
```
java.lang.RuntimeException: [01:38.754] Failed to execute 'DataTable.line' for element 'Result Table' during '15' seconds. Failed to create Line. Headers size='6' is not equal to Elements size='5'
```

<details> 
  <summary>Трейс:</summary>

```
java.lang.RuntimeException: [31:49.880] Failed to execute 'DataTable.line' for element 'Result Table' during '15' seconds. Failed to create Line. Headers size='6' is not equal to Elements size='5'

	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:19)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
	at com.epam.jdi.light.elements.complex.table.DataTable.line(DataTable.java:80)
	at com.bft.aisubp.tests.dicts.FhdPlanStruct.FhdPlanStructTest.cTestFhdPlanStructCreateCopy(FhdPlanStructTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.RuntimeException: Failed to execute 'DataTable.line' for element 'Result Table' during '15' seconds. Failed to create Line. Headers size='6' is not equal to Elements size='5'
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
	at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:636)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:48)
	... 26 more
Caused by: java.lang.RuntimeException: Failed to create Line. Headers size='6' is not equal to Elements size='5'
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:19)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
	at com.epam.jdi.light.elements.complex.table.DataTable.line_aroundBody8(DataTable.java:84)
	at com.epam.jdi.light.elements.complex.table.DataTable$AjcClosure9.run(DataTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:60)
	at com.epam.jdi.light.actions.ActionHelper.stableAction(ActionHelper.java:624)
	... 27 more
Caused by: java.lang.RuntimeException: Failed to create Line. Headers size='6' is not equal to Elements size='5'
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
	at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:19)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
	at com.epam.jdi.light.elements.complex.table.BaseTable.row(BaseTable.java:524)
	at com.epam.jdi.light.elements.complex.table.DataTable.row_aroundBody6(DataTable.java:84)
	at com.epam.jdi.light.elements.complex.table.DataTable$AjcClosure7.run(DataTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:60)
	at com.epam.jdi.light.actions.ActionHelper.defaultAction(ActionHelper.java:610)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:49)
	... 32 more
Caused by: java.lang.RuntimeException: 
Failed to create Line. Headers size='6' is not equal to Elements size='5'
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:16)
	at com.epam.jdi.light.elements.complex.table.Line.<init>(Line.java:68)
	at com.epam.jdi.light.elements.complex.table.BaseTable.row_aroundBody88(BaseTable.java:525)
	at com.epam.jdi.light.elements.complex.table.BaseTable$AjcClosure89.run(BaseTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.epam.jdi.light.actions.ActionObject.execute(ActionObject.java:60)
	at com.epam.jdi.light.actions.ActionHelper.defaultAction(ActionHelper.java:610)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:49)
	... 39 more

```
</details>

Если закомментировать budgetId в ResultRow и ResultRowInfo (выбрал его, так как этот столбец невидим), то вывод такой (все три строки таблицы заполнены одинаковыми значениями):
Дебаггер:
![изображение](https://user-images.githubusercontent.com/15943769/121327318-c6717380-c92c-11eb-87e9-80265d85d8ea.png)
<details> 
  <summary>Лог:</summary>

```
[ INFO 55:28.938] : Get 'Result Table' header
[ INFO 55:28.943] : >>> [Checkbox, Budget Caption, Org Caption, Type Mode, F Type]
[ INFO 55:28.945] : [Checkbox, Budget Caption, Org Caption, Type Mode, F Type]
[ STEP 55:29.049] : Preview 'Result Table' table
[ STEP 55:29.181] : >>> Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов Д...
[ INFO 55:29.198] : 
Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов ДОНМ Тип учреждения Для всех 
Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов Москомэкспертиза Тип учреждения Для всех 
Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов Мосгоризбирком Тип учреждения Бюджетное учреждение
[ STEP 55:29.203] : Get row '1' for 'Result Table' table
[ INFO 55:31.046] : >>> smart: [data-testid='ui-element']
[ STEP 55:31.141] : Get 'Checkbox' text
[ STEP 55:31.235] : >>> 
[ INFO 55:31.254] : 
[ STEP 55:31.258] : Get row '1' for 'Result Table' table
[ STEP 55:31.276] : >>> smart: [data-testid='ui-element']
[ STEP 55:31.307] : Get 'Budget Caption' text
[ STEP 55:31.381] : >>> Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ INFO 55:31.383] : Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ STEP 55:31.407] : Get row '1' for 'Result Table' table
[ STEP 55:31.412] : >>> smart: [data-testid='ui-element']
[ STEP 55:31.417] : Get 'Org Caption' text
[ STEP 55:31.484] : >>> ДОНМ
[ INFO 55:31.512] : ДОНМ
[ STEP 55:31.515] : Get row '1' for 'Result Table' table
[ STEP 55:31.519] : >>> smart: [data-testid='ui-element']
[ STEP 55:31.546] : Get 'Type Mode' text
[ STEP 55:31.607] : >>> Тип учреждения
[ INFO 55:31.608] : Тип учреждения
[ STEP 55:31.613] : Get row '1' for 'Result Table' table
[ STEP 55:31.618] : >>> smart: [data-testid='ui-element']
[ STEP 55:31.622] : Get 'F Type' text
[ STEP 55:31.704] : >>> Для всех
[ INFO 55:31.713] : Для всех

[ STEP 55:31.743] : Get row '2' for 'Result Table' table
[ INFO 55:32.776] : >>> smart: [data-testid='ui-element']
[ STEP 55:32.779] : Get 'Checkbox' text
[ STEP 55:32.996] : >>> 
[ INFO 55:33.022] : 
[ STEP 55:33.048] : Get row '2' for 'Result Table' table
[ STEP 55:33.052] : >>> smart: [data-testid='ui-element']
[ STEP 55:33.094] : Get 'Budget Caption' text
[ STEP 55:33.149] : >>> Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ INFO 55:33.156] : Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ STEP 55:33.187] : Get row '2' for 'Result Table' table
[ STEP 55:33.191] : >>> smart: [data-testid='ui-element']
[ STEP 55:33.201] : Get 'Org Caption' text
[ STEP 55:33.272] : >>> ДОНМ
[ INFO 55:33.318] : ДОНМ
[ STEP 55:33.350] : Get row '2' for 'Result Table' table
[ STEP 55:33.354] : >>> smart: [data-testid='ui-element']
[ STEP 55:33.358] : Get 'Type Mode' text
[ STEP 55:33.423] : >>> Тип учреждения
[ INFO 55:33.429] : Тип учреждения
[ STEP 55:33.460] : Get row '2' for 'Result Table' table
[ STEP 55:33.465] : >>> smart: [data-testid='ui-element']
[ STEP 55:33.481] : Get 'F Type' text
[ STEP 55:33.529] : >>> Для всех
[ INFO 55:33.549] : Для всех
[ STEP 55:33.580] : Get row '3' for 'Result Table' table
[ INFO 55:34.392] : >>> smart: [data-testid='ui-element']
[ STEP 55:34.419] : Get 'Checkbox' text
[ STEP 55:34.523] : >>> 
[ INFO 55:34.524] : 

[ STEP 55:34.527] : Get row '3' for 'Result Table' table
[ STEP 55:34.531] : >>> smart: [data-testid='ui-element']
[ STEP 55:34.603] : Get 'Budget Caption' text
[ STEP 55:34.669] : >>> Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ INFO 55:34.670] : Бюджет города Москвы на 2021 год и плановый период 2022 и 2023 годов
[ STEP 55:34.673] : Get row '3' for 'Result Table' table
[ STEP 55:34.677] : >>> smart: [data-testid='ui-element']
[ STEP 55:34.702] : Get 'Org Caption' text
[ STEP 55:34.769] : >>> ДОНМ
[ INFO 55:34.770] : ДОНМ
[ STEP 55:34.774] : Get row '3' for 'Result Table' table
[ STEP 55:34.778] : >>> smart: [data-testid='ui-element']
[ STEP 55:34.799] : Get 'Type Mode' text
[ STEP 55:34.847] : >>> Тип учреждения
[ INFO 55:34.849] : Тип учреждения
[ STEP 55:34.870] : Get row '3' for 'Result Table' table
[ STEP 55:34.875] : >>> smart: [data-testid='ui-element']
[ STEP 55:34.910] : Get 'F Type' text
[ STEP 55:34.952] : >>> Для всех
[ INFO 55:34.954] : Для всех
```

</details>

**Вопрос: Что нужно изменить в коде, чтобы resultTable верно заполнялся значениями таблицы?**

----

### Дополнительно:
<details> 
  <summary>Отмечу, что я могу с ней работать как с обычной таблицей:</summary>

```
@JTable(root = "//table[@class='ui-jqgrid-btable']",
            header = {"Чекбокс", "ИД", "Бюджет", "Учредитель", "Режим", "Тип учреждения"},
            size = 6
    ) public Table resultTable2;
```

И она нормально функционирует. Например проверка, проходит успешно:
`results.resultTable2.assertThat().rowThat(ColumnMatcher.containsValue("Мосгоризбирком", Column.inColumn("Учредитель")));`

Но мне нужно не только проверять, что таблица содержит значение, но и кликать по одной из ячеек.
Что я бы мог сделать это строкой кода:
`results.resultTable.line(d -> d.orgCaption.contains(orgCaption)).checkbox.click();`
если бы resultTable удалось корректно заполнить значениями таблицы.
</details>

**Comment by StrikS** [comment]
Добавил трейс для java.lang.RuntimeException: [01:38.754] Failed to execute 'DataTable.line' for element 'Result Table' during '15' seconds. Failed to create Line. Headers size='6' is not equal to Elements size='5'

**Comment by RomanIovlev** [comment]
In a message written "Headers size='6' is not equal to Elements size='5'"
Судя по внешнему виду таблицы и html коду у нее 5 видимых столбцов
В Пейджобджекте их 6... поэтому и падает. 
В случае с "формальной таблицей" вы прописали названия колонок и поэтмоу работает, также можно прописать и для DataTable...
Попробуйте добавить аннотацию JTable как в примере с Table для DataTable

**Comment by AlexeyGirin** [comment]
@StrikS подскажи - помогло?

**Comment by pnatashap** [comment]
Была проблема связанная с тем, что в первой колонке нет текста, исправлено в последней версии.
Если проблема воспроизводится, откройте еще один запрос
