### ISSUE TITLE
NullPointerException при WebPage.open(), а точнее WindowsManager.getWindows()

### ISSUE THREAD

**Issue by StrikS** [jdi-testing/jdi-light#2971]
Добрый день
В 30% случаев ВЕСЬ целиком прогон тестов падает ОДНОЙ И ТОЙ ЖЕ ошибкой. И либо падает весь, либо вообще не падет. Не бывает такого, чтобы падала только часть тестов с такой ошибкой.
![изображение](https://user-images.githubusercontent.com/15943769/122897885-d729dc80-d363-11eb-826a-56ac95a169b3.png)
![изображение](https://user-images.githubusercontent.com/15943769/122897901-da24cd00-d363-11eb-80ea-b4a302d96aa0.png)

java.lang.RuntimeException: [39:06.2] java.lang.NullPointerException
        at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
        at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
        at com.epam.jdi.tools.func.JFunc2.execute(JFunc2.java:19)
        at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
        at com.epam.jdi.light.elements.composite.WebPage.open(WebPage.java:219)
        at com.bft.aisubp.tests.other.LoginTest.testSuccessLogin(LoginTest.java:16)
        at com.bft.aisubp.tests.TestsInit.login(TestsInit.java:27)
        at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.epam.jdi.tools.func.JAction1.execute(JAction1.java:22)
        at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:46)
        ... 25 more
Caused by: java.lang.NullPointerException
        at com.epam.jdi.light.elements.common.WindowsManager.getWindows(WindowsManager.java:26)
        at com.epam.jdi.light.actions.ActionHelper.processPage(ActionHelper.java:354)
        at com.epam.jdi.light.actions.ActionHelper.processBeforeAction(ActionHelper.java:220)
        at com.epam.jdi.light.actions.ActionHelper.beforeJdiAction(ActionHelper.java:204)
        at com.epam.jdi.tools.func.JAction1.execute(JAction1.java:20)
        ... 26 more

<details> 
  <summary>Лог:</summary>
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [24] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [28] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.992] : [19] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.992] : [27] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.992] : [22] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.992] : [15] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.992] : [14] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [26] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [18] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [23] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [16] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [21] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [25] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [17] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:49        [ STEP 12:49.993] : [20] Open 'Login Page'(url=http://srv-at-sp-asugf:8099/azk/index.jsp)
build        21-Jun-2021 16:12:50        [ERROR 12:50.472] : [26] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [23] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [24] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.474] : [17] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.474] : [20] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [28] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [25] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [19] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.472] : [27] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [18] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.474] : [21] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.474] : [15] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.474] : [22] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [14] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:12:50        [ERROR 12:50.473] : [16] !>>> Site.loginPage (url=http://srv-at-sp-asugf:8099/azk/index.jsp; title=)
build        21-Jun-2021 16:13:50        [ERROR 13:50.843] : [24] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.843] : [28] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.844] : [19] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.844] : [14] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.844] : [17] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.844] : [18] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.845] : [26] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.846] : [21] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.855] : [23] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.855] : [16] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.858] : [20] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.862] : [15] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.882] : [22] Failed actions chain: 
build        21-Jun-2021 16:13:50        [ERROR 13:50.882] : [25] Failed actions chain: WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp') > WebPage.open(String:'http://srv-at-sp-asugf:8099/azk/index.jsp')
build        21-Jun-2021 16:13:50        [ERROR 13:50.882] : [27] Failed actions chain: 
</details>

<details> 
  <summary>В коде ничего замысловатого:</summary>

   ![изображение](https://user-images.githubusercontent.com/15943769/122898163-18ba8780-d364-11eb-8858-94ac99100cfc.png)
![изображение](https://user-images.githubusercontent.com/15943769/122898180-1ce6a500-d364-11eb-88a4-0360849c1cb8.png)
![изображение](https://user-images.githubusercontent.com/15943769/122898197-1fe19580-d364-11eb-97f9-392d2c13ab64.png)

</details>

Используем selenoid. Селеноид не перегружен, слотов достаточно на нём.
Многопоточный запуск с TestNG (15 потоков обычно).
Версия JDI последняя (1.3.12)
Если еще какя-нибудь информация нужна, то скажите

**Comment by AlexeyGirin** [comment]
Дело в версии селениума. Нужно обновлять до 4.4.0

**Comment by AlexeyGirin** [comment]
Дело в webdrivermanager
Система скачивает драйвер, отчитывается в логе про это, но потом - видимо его куда-то распаковывает, что занимает время и в это время - путь драйвера - NULL что вызывает падение
Нужно вопробовать обновиться до версии [webdrivermanager](https://github.com/bonigarcia/webdrivermanager/releases/tag/webdrivermanager-5.3.0)

**Comment by pnatashap** [comment]
Looks like fixed
