### ISSUE TITLE
Помочь Константину

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3416]
From Konstantin Mazurin:

Привет!
При попытке отправить текст в элемент TextField с помощью метода setValue я получаю ошибку

java.lang.RuntimeException: [31:43.141] Surround method issue: Can't get action name: UIElement.input
at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:31)
at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
at com.jdiai.tools.func.JFunc2.execute(JFunc2.java:19)
at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
at com.epam.jdi.light.elements.interfaces.common.IsInput.input(IsInput.java:16)
at com.epam.jdi.light.ui.html.elements.common.TextArea.setValue(TextArea.java:54)

Версия jdi-light-html: 1.3.17 (в 1.3.14 было то же самое)
В чем может быть проблема?

**Comment by AlexeyGirin** [comment]
Ждём релиз в мавен с фиксом

**Comment by AlexeyGirin** [comment]
Done.
