### ISSUE TITLE
NullPointerException in SetUp method for RadioTests and InitPageTests

### ISSUE THREAD

**Issue by wsbaser** [jdi-testing/jdi-light#3495]
**Test:** io.github.epam.html.tests.elements.complex.RadioTests.before

**StackTrace:**
[03:04.492] Can't get WebDriver
java.lang.RuntimeException: [03:04.492] Can't get WebDriver
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:34)
	at com.epam.jdi.light.actions.ActionHelper.actionFailed(ActionHelper.java:382)
	at com.jdiai.tools.func.JFunc2.execute(JFunc2.java:19)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:55)
	at com.epam.jdi.light.elements.composite.WebPage.verifyUrl(WebPage.java:111)
	at io.github.epam.html.tests.site.steps.States.moveToHomePage(States.java:25)
	at io.github.epam.html.tests.site.steps.States.shouldBeLoggedIn(States.java:19)
	at io.github.epam.html.tests.elements.complex.RadioTests.before(RadioTests.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: 
Can't get WebDriver
	at com.jdiai.tools.func.JAction1.execute(JAction1.java:22)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:46)
	... 20 more
Caused by: java.lang.RuntimeException: 
Can't get WebDriver
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:16)
	at com.epam.jdi.light.elements.common.WindowsManager.getWindows(WindowsManager.java:39)
	at com.epam.jdi.light.actions.ActionHelper.processPage(ActionHelper.java:354)
	at com.epam.jdi.light.actions.ActionHelper.processBeforeAction(ActionHelper.java:220)
	at com.epam.jdi.light.actions.ActionHelper.beforeJdiAction(ActionHelper.java:204)
	at com.jdiai.tools.func.JAction1.execute(JAction1.java:20)
	... 21 more

**Comment by pnatashap** [comment]
@wsbaser Please add a link to Tests and error stacktrace

**Comment by pnatashap** [comment]
Fixed in another task, the reason is async driver loading
