### ISSUE TITLE
UIList.get(0) not waiting list item

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#69]
Precondition:
@Css("list...")
public UIList<Paragraph, ?> paragraphs;

public class Paragraph extends Section {
    @Css("...")
    public Button paragraph;
...
}

paragraphs.get(0) - this method doesn't wait items!

ndex: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.epam.jdi.light.elements.complex.IList.get(IList.java:128)
	at com.cm.pages.DocumentPage.selectParagraph(DocumentPage.java:104)

**Comment by yanusa3** [comment]
1.0.45 - still reproduced
0
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:388)
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:397)
	at com.epam.jdi.light.elements.complex.IList.get(IList.java:125)

**Comment by kasdar23** [comment]
bug is reproduced: package io.github.epam.html.tests.issue.issue69
